spring.application.name=SampleProject-1

spring.datasource.url=jdbc:postgresql://dpg-cvc1l1tumphs73cfpe6g-a.oregon-postgres.render.com:5432/empmgmt_db
spring.datasource.username=empmgmt_db_user
spring.datasource.password=sUloRDlaCR5XWmz8dpb5ENnnTQcrrcmO
#spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect